### ISSUE TITLE
Allow negative x and y values

### ISSUE THREAD

**Issue by KevinW1998** [elbywan/quadtree-lib#2]
I really like this library, but it would be cool if negative x and y values were supported.

**Comment by elbywan** [comment]
Hi Kevin, thanks for the endorsement ;).

Indeed it would be great to have this feature !
Unfortunately I am right now on vacation in Japan for three weeks and I have limited time to work on it (& crappy wifi).

Anyway I will try to take some time for a quick fix, otherwise it is gonna be done when I return.

**Comment by KevinW1998** [comment]
Thank you! Don't pressure yourself, enjoy your vacation. I only use this library right now for a proof-of-concept.

**Comment by elbywan** [comment]
Finally found some time to work on it, should be ok 👍.

**Comment by KevinW1998** [comment]
Seems that there are still issues when constructing a quadtree with negative x and y values.
Constructing a quadtree with
```javascript
new Quadtree({x: -400000, y: -400000, width: 800000, height: 800000, maxElements: 20});
```
will fail with the error `Dimensions and coordinates must be positive integers.`

**Comment by elbywan** [comment]
Ah sorry I misunderstood. 
I thought you wanted negative x/y coordinates for the **elements**, not the quadtree itself.

I just pushed a fix which removes the constraint.
