### ISSUE TITLE
`Cannot read property 'get' of undefined` at push.

### ISSUE THREAD

**Issue by afska** [elbywan/quadtree-lib#3]
I'm having a **random** problem when I do:
```js
this.collision = {
  x: this.position.x,
  y: this.position.y,
  width: this.width,
  height: this.height
};
quadtree.push(this.collision, true);
```

It works fine 90% of the time but sometimes I get:
```
Uncaught TypeError: Cannot read property 'get' of undefined
e.pushAll @ quadtree.min.js:1
e.push @ quadtree.min.js:1
_addToQuadtree @ PewPew.js:67
```

and that error makes the whole game crash. Any help?

Thanks!

**Comment by elbywan** [comment]
Hi Rodrigo !

I cannot tell for sure with only this portion of code, but I can try ;).

Do you have a construct like this in your code ?

```javascript
quadtree.each(item => item.x = item.x + 1)
````

If so, it is very likely to fail (with the very same error that you pasted).

When you push with the `observe`flag, every time you set any of the x/y/width/height properties the element will be removed/pushed back in the Quadtree.

If you are iterating at the same time, it will mess things up, like subtrees could have been removed or added during the update.

But, you can iterate on a separate array containing the items you want to update instead.

```javascript
/* Observe flag (slower) */
var moving = []
// Better to have a separate array reference 
// but for the sake of the example I'm filling it with the Quadtree contents
quadtree.each(elt => {
    moving.push(elt)
})
moving.forEach(elt => {
    elt.x = (elt.x + 1)
    elt.y = (elt.y + 1)
})
```

*By the way, if you have a lot of items to update, do not use the observe flag, it is much slower as it removes/adds every single element instead of adding them all with pushAll.*

```javascript
/* No observe flag (faster) */
var moving = []
quadtree.each(elt => {
    moving.push(elt)
})
moving.forEach(elt => {
    quadtree.remove(elt)
    elt.x = (elt.x + 1)
    elt.y = (elt.y + 1)
})
quadtree.pushAll(moving)
```

**Comment by afska** [comment]
Hey @elbywan thanks for your help :smiley: 

I'll give you more detail:

I have `Attack` objects in a pool (I reuse the instances for performance). Something like this (simplifying / pseudocode):
```js
class Attack extends Phaser.Sprite {
  constructor(game, x, y) {
    super(game, x, y);

    this.collision = {
      x: this.position.x,
      y: this.position.y,
      width: this.width,
      height: this.height,
      instance: this
    };
  }

  update(delta) {
    this.move(this.speed * delta, 0); 
  }

  move(dx, dy) {
    this.position.x += dx;
    this.position.y += dy;

    this.collision.x = this.position.x;
    this.collision.y = this.position.y;
  }

  attach() {
    this.isSoftDelete = false;
    this.visible = true;

    this.game.quadtree.push(this.collision, true);
  }

  detach() {
    this.isSoftDelete = true;
    this.visible = false;

    this.game.quadtree.remove(this.collision);
  }
}
```

... in `Game`:
```js
class Game {
  constructor() {
    this.quadtree = new Quadtree(...)
  }

  loop(delta) {
    update(delta)
    render(delta)
  }

  update(delta) {
    for (let enemy of this.enemies) {
      for (let { instance } of this.quadtree.colliding(enemy) {
        if (!attack.isSoftDelete) attack.detach();
      }
    }
  }
}
```

As you can see, the `update` method executes first on attacks (moving each one and leaving to `quadtree-lib` the work of updating the quadtree) and then, iterating over the result of `colliding(enemy)` only soft-deleting the entities (removing them from the tree).

It doesn't seems to be the case you mentioned in your reply :confused: 

Are you doing something asynchronous after the push or when I change the `x` and `y` values?

**Comment by elbywan** [comment]
> Are you doing something asynchronous after the push or when I change the x and y values?

Nope, everything is synchronous using getters and setters to *observe* the element and remove/push when x/y/width/height properties are updated.

Your code seems allright, though I'm positive that the error only happens when a coordinate or dimension is modified while the element is still inside the tree (proper way is : removal -> update -> insert).

I committed a fix correcting the fact that a manual removal did **not** remove getters and setters used to observe elements. 
Thus, an observed element which was manually removed from the tree would still be pushed back in if its coordinates/dimensions were changed afterwards.

As you manually remove Attacks from the tree in the `detach` method and reuse them, it might fix your issue.

Could you retry with the latest commit in the master branch ? (`npm install elbywan/quadtree-lib#master`)

Thanks !

**Comment by afska** [comment]
Oh, great. It works perfectly now! Thanks!

I'll try to improve the code to do the updates in batches like you said, for better performance.

By the way, is there any method to check collisions without allocating a new array each time? I think it's very expensive for the garbage collector to do that in the render loop 60 times by second.

I mean, instead of:
```js
for let x in this.quadtree.colliding(enemy)
  ...
```

It would be great to have:
```js
this.quadtree.forEachCollition(enemy, this._removeAttack);
```

so I don't have a new array allocation each time.

**Comment by elbywan** [comment]
>is there any method to check collisions without allocating a new array each time? 

I just made one 😉 (as with the last one, committed on the master branch).

```javascript
onCollision(
    {x: 10, y: 20}, // Collision
    function(item) { /* Action on colliding item */ },
    function(element1, element2) {
       // Optional collision algorithm
})
```

In your case : 
```javascript
 this.quadtree.onCollision(enemy, this._removeAttack); // might need a "this" context binding
```

The catch is that this is an iterative function, which means that you should not usually change the quadtree or its elements in the callback.

**But** in your use case you **only** remove elements (Attacks), and after having a quick look at the implementation of the iteration I'm thinking that it will be allright 👍 .

**Comment by afska** [comment]
It works :)
Thanks! It's a great library.

I'll close the issue. Can you `npm publish` that?

**Comment by elbywan** [comment]
Just published a new release.

Thank you very much for your support 😄 .
