### ISSUE TITLE
Object pooling advice

### ISSUE THREAD

**Issue by Arcanorum** [elbywan/quadtree-lib#6]
I'm making a game where players can run around and shoot stuff, spawning new entities that have physics bodies that I need to check for collisions against.

These dynamic entities (things that can be added to _and_ removed from the game world) are pooled, so whenever something is "destroyed", is it just deactivated so it doesn't interact with anything, and returned to the pool. There is no actual deletion of the objects for dynamic entities, only reuse.

Adding to and removing from the quadtree every time an entity is recycled seems like a bad idea. Is adding to/removing from the tree even a big deal performance-wise?
If so, is there a way to "deactivate" an element in the tree but not have it removed, so it can be quickly turned back on again and reused.
I realise this is probably outside the scope of this lib.

**Comment by elbywan** [comment]
Hi @Arcanorum,

Hope these answers will help you :

>Is adding to/removing from the tree even a big deal performance-wise?

Yes if you plan to remove/add a big bunch of entities (several thousands) around 60 times per second. Shouldn't be an issue otherwise.

>If so, is there a way to "deactivate" an element in the tree but not have it removed, so it can be quickly turned back on again and reused.

The quadtree items are all yours to modify, so I think you could add a "disabled" flag to mark the deactivated items (those returned to the pool).

Then either :
- use a [custom collision algorithm](https://github.com/elbywan/quadtree-lib#retrieve-colliding-elements) to simply ignore the items marked with the flag
- or simply iterate over the collision results and skip the deactivated items
