### ISSUE TITLE
What are "Oversized elements"

### ISSUE THREAD

**Issue by Arcanorum** [elbywan/quadtree-lib#9]
Can you add some documentation about what oversized elements are? What is considered oversized? How do they behave different from "regular" sized elements?

**Comment by elbywan** [comment]
> Can you add some documentation about what oversized elements are?

Oversized elements are elements which cannot make a quadtree node "split" in four because they are too big to fit. They are stored in the node instead of being dispatched to the leaves.

In this [demo](http://elbywan.github.io/quadtree-lib/demo/basic/basic.html), the "oversized" elements are coloured in purple. Regular elements are coloured in red.

> How do they behave different from "regular" sized elements?

For a library consumer point of view, you shouldn't see any significant difference !
